<?php

namespace App\Commands;

use App\Services\FrontmatterParser;
use LaravelZero\Framework\Commands\Command;
use Symfony\Component\Finder\Finder;

class NoteListCommand extends Command
{
    protected $signature = 'note:list
        {--project= : Filter by project}
        {--vault= : Vault path, defaults to OBSIDIAN_VAULT / notes.vault config}';

    protected $description = 'List notes generated by Claude Code in a vault';

    public function handle(): int
    {
        $vault = $this->option('vault') ?: config('notes.vault');

        if (! $vault || ! is_dir($vault)) {
            $this->components->error('Vault path missing or does not exist. Pass --vault or set OBSIDIAN_VAULT.');

            return self::FAILURE;
        }

        $projectFilter = $this->option('project');
        $found = false;

        foreach ((new Finder)->files()->in($vault)->name('*.md') as $file) {
            $frontmatter = FrontmatterParser::parse($file->getContents());

            if (($frontmatter['source'] ?? null) !== 'claude-code') {
                continue;
            }

            if ($projectFilter && ($frontmatter['project'] ?? null) !== $projectFilter) {
                continue;
            }

            $found = true;
            $this->components->twoColumnDetail(
                $frontmatter['title'] ?? $file->getFilenameWithoutExtension(),
                $frontmatter['project'] ?? '-'
            );
        }

        if (! $found) {
            $this->components->warn('No Claude Code notes found.');
        }

        return self::SUCCESS;
    }
}
